$(document).ready(function(){
	$(".edit_name").click(function(){
		$(".supplierName").hide();
		$(".edit_name").hide();
		$(".updatename").show();
		$(".closeedit_name").show();
	});
	$(".closeedit_name").click(function(){
		$(".supplierName").show();
		$(".edit_name").show();
		$(".updatename").hide();
		$(".closeedit_name").hide();
	});
	$(".edit_addressLine1").click(function(){
		$(".supplieraddressLine1").hide();
		$(".edit_addressLine1").hide();
		$(".updateaddressLine1").show();
		$(".closeedit_addressLine1").show();
	});
	$(".closeedit_addressLine1").click(function(){
		$(".supplieraddressLine1").show();
		$(".edit_addressLine1").show();
		$(".updateaddressLine1").hide();
		$(".closeedit_addressLine1").hide();
	});
	$(".edit_addressLine2").click(function(){
		$(".supplieraddressLine2").hide();
		$(".edit_addressLine2").hide();
		$(".updateaddressLine2").show();
		$(".closeedit_addressLine2").show();
	});
	$(".closeedit_addressLine2").click(function(){
		$(".supplieraddressLine2").show();
		$(".edit_addressLine2").show();
		$(".updateaddressLine2").hide();
		$(".closeedit_addressLine2").hide();
	});
	$(".edit_postcode").click(function(){
		$(".supplierpostcode").hide();
		$(".edit_postcode").hide();
		$(".updatepostcode").show();
		$(".closeedit_postcode").show();
	});
	$(".closeedit_postcode").click(function(){
		$(".supplierpostcode").show();
		$(".edit_postcode").show();
		$(".updatepostcode").hide();
		$(".closeedit_postcode").hide();
	});
	$(".edit_phone").click(function(){
		$(".supplierphone").hide();
		$(".edit_phone").hide();
		$(".updatephone").show();
		$(".closeedit_phone").show();
	});
	$(".closeedit_phone").click(function(){
		$(".supplierphone").show();
		$(".edit_phone").show();
		$(".updatephone").hide();
		$(".closeedit_phone").hide();
	});
});